kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nginx-www-apps
spec:
  host: nginx.www-apps.jnphub01.dev06.red-chesterfield.com
  to:
    kind: Service
    name: placement-nginx-service
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect


