---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: pacman-ansible-demo
  name: pacman-ansible-demo-placement-0
  namespace: pacman
spec:
  clusterSelector:
    clusterReplicas: 2
    matchExpressions:
    - key: region
      operator: In
      values:
      - us-east-1
      - centralus
      - europe-west3
  #  matchLabels:
  #    'cloud': 'Google'
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
