---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: ansible/pacman
  labels:
    app: pacman-ansible-demo
  name: pacman-ansible-demo-subscription-0
  namespace: pacman
spec:
  hooksecretref: 
    name: toweraccess
  channel: nginx-ansible-demo-demo-subscription-gitops-chn-ns-0/nginx-ansible-demo-demo-subscription-gitops-chn-0
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-ansible-demo-placement-0

