apiVersion: v1                    
kind: Namespace
metadata:
  name: book-import                             
---
apiVersion: v1                      
kind: Namespace
metadata:
    name: book-import-demo-subscription-gitops-chn-ns-0
    