---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: book-import/app
  labels:
    app: book-import
  name: book-import-subscription-0
  namespace: book-import
spec:
    channel: book-import-demo-subscription-gitops-chn-ns-0/book-import-demo-subscription-gitops-chn-0
    placement:
      placementRef:
        kind: PlacementRule
        name: book-import-placement-0

