---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      name: nginx-placement
      namespace: nginx
    spec:
      selector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - nginx-placement
      componentKinds:
      - group: app.ibm.com/v1alpha1
        kind: Subscription