apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-placement
  namespace: nginx
  labels:
    app: nginx-placement
spec:
  #clusters:
  #- name: gcp1-hive
  clusterSelector:
    matchLabels:
      vendor: Openshift
  #clusterReplicas: 1  #Apply to how many matched clusters, default is ALL
